parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MailDataProvider\MailDataProvider: ~

    App\Service\MailDataProvider\MailDataProviderInterface: '@App\Service\MailDataProvider\MailDataProvider'

    App\Service\MailSender\MailSender: ~

    App\Service\MailSender\MailSenderInterface: '@App\Service\MailSender\MailSender'